version: "3"

services:
  bot:
    build: .
    command: python run.py
    depends_on:
      - db
    volumes:
      - ./:/opt/artemis
    environment:
      - JISHAKU_HIDE=true

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
      - ./data/postgres:/var/lib/postgresql/data
